services:
  db:
    image: postgres:15
    container_name: my_postgres
    environment:
      POSTGRES_DB: students
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - "./volumes/db/data:/var/lib/postgresql/data"

